sudo: true
language: javascript
services:
 - docker
before_install:
  - docker pull icambron/luxon
  - ./docker/npm-ci install
script:
  - ./docker/npm-ci run build
  - ./docker/npm-ci run lint
  - ./docker/npm-ci run test
  - ./docker/npm-ci run docs
  - ./docker/npm-ci run check-doc-coverage
branches:
  only:
    - master
